name: Daily Secret Knowledge Tidbits

on:
  schedule:
    - cron: '0 9 * * *'  # Runs at 9 AM UTC daily
  workflow_dispatch:      # Allows manual triggering

jobs:
  send-tidbits:
    runs-on: ubuntu-latest
    env:
      LLM_GEMINI_KEY: ${{ secrets.GOOGLE_API_KEY }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests llm sendgrid markdown
        llm install llm-gemini
      
    - name: Run tidbits script
      env:
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
      run: |
        # Run in non-test mode
        python -c "
        from tidbits import SecretKnowledgeTidbits
        processor = SecretKnowledgeTidbits('https://raw.githubusercontent.com/trimstray/the-book-of-secret-knowledge/refs/heads/master/README.md')
        processor.run(test_mode=False)
        "